apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: word-convert-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: wordconvert-test.test.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: word-convert-service
                port:
                  number: 80
